# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('owner', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_type', models.CharField(choices=[('USD', 'US Dollar'), ('AUD', 'Austrilian Dollar'), ('CNY', 'China National Yuan')], default='CNY', max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(verbose_name='date published')),
                ('exchange_rate', models.FloatField(default=1.0)),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch_finacial_data.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch_finacial_data.Bank'),
        ),
        migrations.AddField(
            model_name='account',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetch_finacial_data.Currency'),
        ),
    ]
