# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_finacial_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
