# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_finacial_data', '0002_account_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
