# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_finacial_data', '0003_auto_20161128_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_abbreviation', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_abbreviation',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
    ]
