# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_finacial_data', '0005_account_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_availible',
            field=models.BooleanField(default=True),
        ),
    ]
