# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_finacial_data', '0006_account_is_availible'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.FloatField(default=0.003),
        ),
        migrations.AddField(
            model_name='account',
            name='mature_date',
            field=models.DateTimeField(null=True),
        ),
    ]
