# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetch_finacial_data', '0007_auto_20161130_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
